#
# Copyright (c) 2025, BlackBerry Limited. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ROOT_DIR := $(notdir $(CURDIR))
ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)


.PHONY: all clean fonts icons

all: $(if $(wildcard icons/*),icons) $(if $(wildcard fonts/*),fonts)

fonts:
	$(MAKE) -Cfonts

icons:
	$(MAKE) -Cicons

clean:
	$(MAKE) -Cfonts clean
	$(MAKE) -Cicons clean

-include $(BUILD_TEMPLATE)/template.mk
