#!/bin/bash
# While not providing an option, this script is still run along with other option scripts.
#
# It provides a way to hook mkqnximage after it does its initial generation

function configure()
{
    rc=0

    # Generate hook so that this gets called with 'generate'
    cat >>output/option_files/options.cti <<EOF
GENERATE_SCRIPT="${BASH_SOURCE[0]}"
EOF
}

function postgen()
{
    # By default, mkqnximage creates a passwd file that uses /bin/sh.
    # We want it to be /bin/bash so post-process it now.
    if [ -e output/build/passwd ]; then
        echo "CTI: Post-processing output/build/passwd"
        sed -i "s/\/bin\/sh/\/bin\/bash/" output/build/passwd
    fi

    # By default, mkqnximage allows root-login via ssh using cert authentication.
    # We don't want to allow it at all so add the switch to disallow root via
    # ssh. Insert the proper configuration into sshd_config. Made a little more
    # difficult as that is an inline file in system.build
    if [ -e output/build/system.build ]; then
        echo "CTI: Post-processing output/build/system.build"
        sed -i -e '/sshd_config={/,/^}/{/sshd_config={/aPermitRootLogin no' -e '}' output/build/system.build
    fi
}

case "$1" in
	configure)
		configure;;
	postgen)
		postgen;;
esac
